/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'userNotFound' : null } |
  { 'irisMismatch' : null } |
  { 'internalError' : null } |
  { 'success' : null } |
  { 'invalidCredentials' : null };
export type AuthToken = bigint;
export interface UserData {
  'id' : UserId,
  'username' : string,
  'irisTemplate' : string,
  'passwordHash' : string,
  'registeredAt' : bigint,
}
export type UserId = bigint;
export interface _SERVICE {
  'getAllUsernames' : ActorMethod<[], Array<string>>,
  'getAllUsers' : ActorMethod<[], Array<UserData>>,
  'getOldestUser' : ActorMethod<[], UserData>,
  'getProfile' : ActorMethod<[AuthToken], UserData>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'login' : ActorMethod<
    [string, string, string],
    { 'result' : AuthResult, 'token' : [] | [AuthToken] }
  >,
  'register' : ActorMethod<[string, string, string], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];