/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const UserData = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'irisTemplate' : IDL.Text,
  'passwordHash' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const AuthToken = IDL.Nat;
export const AuthResult = IDL.Variant({
  'userNotFound' : IDL.Null,
  'irisMismatch' : IDL.Null,
  'internalError' : IDL.Null,
  'success' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});

export const idlService = IDL.Service({
  'getAllUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserData)], ['query']),
  'getOldestUser' : IDL.Func([], [UserData], ['query']),
  'getProfile' : IDL.Func([AuthToken], [UserData], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'result' : AuthResult, 'token' : IDL.Opt(AuthToken) })],
      [],
    ),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuthResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const UserData = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'irisTemplate' : IDL.Text,
    'passwordHash' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const AuthToken = IDL.Nat;
  const AuthResult = IDL.Variant({
    'userNotFound' : IDL.Null,
    'irisMismatch' : IDL.Null,
    'internalError' : IDL.Null,
    'success' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  
  return IDL.Service({
    'getAllUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserData)], ['query']),
    'getOldestUser' : IDL.Func([], [UserData], ['query']),
    'getProfile' : IDL.Func([AuthToken], [UserData], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'result' : AuthResult, 'token' : IDL.Opt(AuthToken) })],
        [],
      ),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuthResult], []),
  });
};

export const init = ({ IDL }) => { return []; };