/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = bigint;
export type AuthToken = bigint;
export interface UserData {
    id: UserId;
    username: string;
    irisTemplate: string;
    passwordHash: string;
    registeredAt: bigint;
}
export enum AuthResult {
    userNotFound = "userNotFound",
    irisMismatch = "irisMismatch",
    internalError = "internalError",
    success = "success",
    invalidCredentials = "invalidCredentials"
}
export interface backendInterface {
    getAllUsernames(): Promise<Array<string>>;
    getAllUsers(): Promise<Array<UserData>>;
    getOldestUser(): Promise<UserData>;
    getProfile(token: AuthToken): Promise<UserData>;
    isUsernameAvailable(username: string): Promise<boolean>;
    login(username: string, passwordHash: string, irisTemplate: string): Promise<{
        result: AuthResult;
        token?: AuthToken;
    }>;
    register(username: string, passwordHash: string, irisTemplate: string): Promise<AuthResult>;
}
import type { AuthResult as _AuthResult, AuthToken as _AuthToken } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllUsernames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsernames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsernames();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getOldestUser(): Promise<UserData> {
        if (this.processError) {
            try {
                const result = await this.actor.getOldestUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOldestUser();
            return result;
        }
    }
    async getProfile(arg0: AuthToken): Promise<UserData> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async login(arg0: string, arg1: string, arg2: string): Promise<{
        result: AuthResult;
        token?: AuthToken;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1, arg2);
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1, arg2);
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string, arg2: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2);
                return from_candid_AuthResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2);
            return from_candid_AuthResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuthToken]): AuthToken | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _AuthResult;
    token: [] | [_AuthToken];
}): {
    result: AuthResult;
    token?: AuthToken;
} {
    return {
        result: from_candid_AuthResult_n2(_uploadFile, _downloadFile, value.result),
        token: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.token))
    };
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userNotFound: null;
} | {
    irisMismatch: null;
} | {
    internalError: null;
} | {
    success: null;
} | {
    invalidCredentials: null;
}): AuthResult {
    return "userNotFound" in value ? AuthResult.userNotFound : "irisMismatch" in value ? AuthResult.irisMismatch : "internalError" in value ? AuthResult.internalError : "success" in value ? AuthResult.success : "invalidCredentials" in value ? AuthResult.invalidCredentials : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
